version: '3.8'

networks:
  app-network:
  queue-network:

volumes:
  app-data:
  redis_data:

services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:
      queue-network:
    depends_on:
      - backend
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: korvax
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      queue-network:
    volumes:
      - redis_data:/data:cached

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mysql
    volumes:
      - ./:/var/www
    networks:
      app-network:
      queue-network:

